/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:45d5f34a-f275-47c9-b5fe-8ad6e76fc743",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_CDJU8RER6",
    "aws_user_pools_web_client_id": "2tdq65fqopnk0gnka4k8tq0buv",
    "oauth": {}
};


export default awsmobile;
